### ISSUE TITLE
FireFly fails to index an ERC-20 token on a public chain

### ISSUE THREAD

**Issue by nguyer** [hyperledger/firefly#1023] opened 2022-08-30 21:17 UTC
I set up a new FireFly stack locally, pointed at a remote RPC node on Polygon Mumbai testnet. I attempted to index an existing token https://mumbai.polygonscan.com/address/0x2d7882beDcbfDDce29Ba99965dd3cdF7fcB10A1e on the chain by creating a token pool:

```
{
  "config": {
    "address": "0x2d7882beDcbfDDce29Ba99965dd3cdF7fcB10A1e",
    "blockNumber": "133000",
    "uri": "firefly://"
  },
  "name": "TestToken",
  "symbol": "TST",
  "type": "fungible"
}
```

I expected to see token transfer events in my FireFly explorer, but they did not show up. I noticed FireFly Core logged the following:

```
[2022-08-30T17:11:52.763Z] DEBUG Received token-transfer event  pid=1 proto=fftokens role=event-loop
[2022-08-30T17:11:52.763Z] ERROR transfer event is not valid - missing data: {"amount":"1000000000000000000","blockchain":{"id":"000001447325/000000/000000","info":{"address":"0x2d7882bedcbfddce29ba99965dd3cdf7fcb10a1e","blockNumber":"1447325","logIndex":"0","signature":"Transfer(address,address,uint256)","transactionHash":"0x2c7d23f5266d6ab08cdd6c7dee3bc48740730f41830ed357533b16140409d328","transactionIndex":"0"},"location":"address=0x2d7882bedcbfddce29ba99965dd3cdf7fcb10a1e","name":"Transfer","output":{"from":"0xe84d601e5d945031129a83e5602be0cc7f182cf3","to":"0x67cf1dc639746ca6d0436aa44ef53f9ec5abd5a8","value":"1000000000000000000"},"signature":"Transfer(address,address,uint256)","timestamp":"2020-07-09T14:44:33Z"},"data":"","from":"0xe84d601e5d945031129a83e5602be0cc7f182cf3","id":"000001447325/000000/000000","poolData":"default","poolLocator":"address=0x2d7882beDcbfDDce29Ba99965dd3cdF7fcB10A1e\u0026schema=ERC20NoData\u0026type=fungible","to":"0x67cf1dc639746ca6d0436aa44ef53f9ec5abd5a8"} pid=1 proto=fftokens role=event-loop
```

Logs are attached.
[firefly_core.log](https://github.com/hyperledger/firefly/files/9456695/firefly_core.log)
[evmconnect.log](https://github.com/hyperledger/firefly/files/9456696/evmconnect.log)
[signer.log](https://github.com/hyperledger/firefly/files/9456697/signer.log)
[tokens.log](https://github.com/hyperledger/firefly/files/9456698/tokens.log)

**Comment by peterbroadhurst** [comment] 2022-08-30 21:21
Assigning this to @awrichar to consider the intended behavior here for indexing historical public chain token transfers.

JSON/RPC endpoint used here could not find that transaction by hash, and returned `null` - which is expected for a historical transaction like this if the JSON/RPC endpoint was not a full archive node:

```
[2022-08-30T17:11:52.115Z] ERROR evmconnect: Failed to get transaction info for TX '0x2c7d23f5266d6ab08cdd6c7dee3bc48740730f41830ed357533b16140409d328': <nil> eventstream=0182efbb-4074-b14f-4a30-875c9d73eb3c
```

**Comment by peterbroadhurst** [comment] 2022-08-31 13:23
Discussed with @vdamle and @awrichar that this is simply expected behavior on non-archive JSON/RPC endpoints. The ability to look up historical transactions is not assured, and as a result the ability to find out who submitted the transaction that resulted in a given event is not assured.

So I've worked on #1026 to allow the signer to be null in FireFly. This is significantly better behavior than ignoring these transfers (with logging) and as a result calculating incorrect balances etc.

**Closed** 2022-09-01 02:37 UTC
