### ISSUE TITLE
Improved event sequencing and dispatching

### ISSUE THREAD

**Issue by peterbroadhurst** [hyperledger/firefly#508] opened 2022-02-10 22:55 UTC
In https://github.com/hyperledger/firefly/issues/493#issuecomment-1035538293 we found  we missed an event due to the dispatcher skipping past events:

```
[2022-02-10T20:32:14.213Z] DEBUG Dispatcher event state: readahead=0 candidates=5 matched=5 inflight=0 queued=0 dispatched=5 dispatchable=0 lastAck=37559 nacks=0 highest=37559 pid=1 role=ed[d2ff7b72-504d-40dd-ab3e-e325c2b7a5d9] sub=3cf508e4-21a7-4f00-8ad0-a6d08a0703d0/default:perf_54c7faaf-ad...
[2022-02-10T20:32:14.366Z] DEBUG Dispatcher event state: readahead=0 candidates=1 matched=0 inflight=0 queued=0 dispatched=0 dispatchable=0 lastAck=0 nacks=0 highest=37595 pid=1 role=ed[d2ff7b72-504d-40dd-ab3e-e325c2b7a5d9] sub=3cf508e4-21a7-4f00-8ad0-a6d08a0703d0/default:perf_54c7faaf-ad...
```

The root cause here is we are writing events concurrently in many goroutines, using different DB transactions - so it's not possible to detect the order of those via a separate DB listener.

In this issue we will track the solution.

**Comment by peterbroadhurst** [comment] 2022-02-10 23:12
After lots of thinking on variations to the below (depending on how we manage connections, and who's in charge of generating the sequence numbers) - it felt like it comes to down to three main options (having pre-ruled out blocking V1.0 for the introduction of NATS/Redis or other similar persistent queue technology as a pre-req of running core):

## 1) Have a single go routine writing to the DB, to ensure the commits are clear

- Pros:
    - No change to event detection logic
- Cons:
    - The DB transactions are separate, so it's hard to work out which to do first - emit the event, or complete the updates in the DB that the event relates to
    - SQLite cannot handle multiple concurrent DB connections, so (with SQLite at least) you cannot block the main business logic routine waiting for the flush of the event

## 2) Update event detector to block until any gaps are filled

- Pros:
   - No change to event emission logic
- Cons:
   - If there is ever a case that we have a gap legitimately - such as a DB rollback - we need a recovery procedure

**Comment by awrichar** [comment] 2022-02-10 23:21
Possibly a variation on (1) - have a single Event Queue that is responsible for writing events to the database. Any place in the code that needs to write an event does it through this queue. Its `AddEvent` method would take an `Event` and also a callback which can contain arbitrary database logic. These events would be written to the database in the order they are queued, and each event would be written transactionally with the other logic supplied.

This would allow callers to include the database operation that marks a thing "done" alongside the event itself (such as moving a message to "confirmed"). If there's a crash or restart, things that weren't completed should be parsed again and it should pick up where it left off.

**Comment by awrichar** [comment] 2022-02-10 23:24
Hmm but moving the event queue to another thread will introduce other issues. Some callbacks, such as `TokensTransferred`, rely on all processing to be done successfully and synchronously before the connector event is ack'd. Moving the event logic out of that flow means the ack may get sent prematurely - you could lose the event if you crash after acking but before the event queue is flushed.

**Comment by awrichar** [comment] 2022-02-10 23:28
Guess the sender could block waiting on the event queue to process its event though. So the sender does as much upfront database logic as it can, then ends any database transaction, then submits the final step(s) to the Event Queue along with the Event, and blocks until that item is processed.

**Comment by awrichar** [comment] 2022-02-10 23:40
Another option: It's possible this could be handled at the database plugin level - for instance, Postgres should be able to enforce it with table-level locks within transactions that insert events. But unsure if pushing it to the database is the right answer here?

**Comment by awrichar** [comment] 2022-02-10 23:54
While we don't want to put too many restrictions on the database implementation in a general sense, I think it could be valid to say that the event storage in particular must be able to sequence things reliably (and that storage can be a database with locks, or a true event queue like Redis). Just one angle to consider.

**Comment by peterbroadhurst** [comment] 2022-02-11 00:05
Ok, this is really helpful. Let me to spend a bunch more time pondering.

I'm thinking about the laws of physics of events (things that would be true even if we were using a separate event system) - one thing has to logically happen "first" in an at-least-once delivery context.

So the trade-off on the design is between:

a) Guaranteeing the order is going to be the same for all consumers of the event
b) Losing the event in the case of a crash scenario, without repeating the action
c) Emitting the event before the thing the event relates to, is flushed to the DB
d) Delaying the event stream

I assert that (b) is most worrying, and then (c) is the most painful for applications to develop around.

So I'd like to focus on a solution that compromises most on (a) and (d).

Thinking it through, I believe (2) is actually the right approach - with a sufficiently long delay to handle gaps in the stream.

**Comment by awrichar** [comment] 2022-02-11 01:03
> sufficiently long delay

picking this number is the real trick 😉

**Comment by peterbroadhurst** [comment] 2022-02-11 02:03
Yeah - understood. I've added a commit here: https://github.com/hyperledger/firefly/pull/501/commits/27637e470f9d8509da8c31bab00949dbd7eb798f

The number picked there is 30secs. This means in the case of a database rollback, we might stall the transaction stream for 30seconds. I was thinking we can add rollback detection and emission over a channel to this code to negatively fill gaps - if that becomes a problem. Because the sequence is something we return on inserts.

**Comment by awrichar** [comment] 2022-02-11 02:17
I agree with the risk analysis, btw. Seems like we're solving both (b) and (c) with database transactions, in both the current code and any proposed solutions (ie the event and the thing it references are committed in the same database transaction). That will actually require a re-think if we move to another eventing system, right?

So the proposed solution strongly enforces that the `seq` assigned by the database is increasing in a contiguous manner, and pauses for 30 sec if it ever skips. I know that's generally true, but I still have some qualms about this approach... and I wonder how it would stack up against a database locking solution. In both cases we're putting a rule on how the database layer behaves, and we're blocking for some amount of time during parallel inserts to ensure strong ordering. Feels a bit like a lock by another name 🤔

**Comment by peterbroadhurst** [comment] 2022-02-11 02:22
Look forward to discussing it a bit more with a whiteboard tomorrow.

> That will actually require a re-think if we move to another eventing system, right?

Yeah - that's definitely not lost on me - and potentially it means an analysis of each place we emit an event, and splitting DB transactions up. I'd like to find something that lets us have an acceptable approach for now, and address that later.

**Comment by peterbroadhurst** [comment] 2022-02-11 02:28
Maybe we can try a test with an `EXCLUSIVE` table lock on the `events` table being added to any transaction that inserts into the events table, as another data point on the journey.

**Comment by peterbroadhurst** [comment] 2022-02-11 02:34
... although even with that, I'm not sure we're guaranteed of consecutive sequences - if we let the database allocate the sequence - so that might combine with sequence allocation in a leader-elected / singleton FireFly runtime.

**Comment by peterbroadhurst** [comment] 2022-02-11 02:35
> It is possible to build gapless assignment by using exclusive locking of a table containing a counter; but this solution is much more expensive than sequence objects, especially if many transactions need sequence numbers concurrently.

**Comment by peterbroadhurst** [comment] 2022-02-11 03:01
And a good blog, that confirms the understanding and trade-offs discussed throughout here (including an example of what "using exclusive locking of a table containing a counter" looks like):
https://www.cybertec-postgresql.com/en/gaps-in-sequences-postgresql/

**Comment by awrichar** [comment] 2022-02-11 12:46
> a test with an EXCLUSIVE table lock on the events table being added to any transaction that inserts into the events table

Yea, this is exactly what I was thinking. Seems like the other notes confirm this would generate a stable sequence at the expense of performance, which I think is what we're trying to achieve in this case.

**Comment by peterbroadhurst** [comment] 2022-02-11 12:59
ok - we had a positive run with the code that expects gapless sequences under normal operation, and tries to cope with them via delay.
I'm stashing that in this branch: https://github.com/kaleido-io/firefly/tree/gapless-sequences

Then let's give an `EXCLUSIVE` table lock a go, as a way to not rely on a _gapless_ sequence - rather just what the DB intents to supply which is a sequence that increases (post commit).

**Comment by peterbroadhurst** [comment] 2022-02-11 13:32
Created this commit for the exclusive lock test: https://github.com/kaleido-io/firefly/commit/1d3cc7d1de4f9bb61b9701595c92d1f076363f17

**Comment by awrichar** [comment] 2022-02-11 15:23
Yeah, good distinction that the locking solution blocks the writers instead of the reader.

I'm still hung up on the first solution because it introduces a tight binding between the application code and the implementation details of the database sequencer, and because it still carries a small risk of (b) due to the "give up after X seconds" clause.

My impression is that the locking solution brings the (b) risk to zero, but at the expense of much lower write performance during high write load.

Probably getting into hand-wavy territory here though without measuring it.

**Closed** 2022-05-31 14:47 UTC
