### ISSUE TITLE
FireFly 1.3 Performance Testing

### ISSUE THREAD

**Issue by SamMayWork** [hyperledger/firefly#1465] opened 2024-02-14 13:51 UTC
Doing performance testing ahead of the 1.3 release following the example set in https://github.com/hyperledger/firefly/issues/563#issuecomment-1123969295. It's worth noting that we don't have an RC at the moment so this is most preliminary testing, but good to get some figures on the board.

Setup is the same as in the older performance testing issue:

2 FireFly nodes on one virtual server (EC2 m4.xlarge)
Entire FireFly stack is local to the server (ie both blockchains, Postgres databases, etc)
Single geth node with 2 instances of ethconnect
Maximum time to confirm before considering failure = 1 minute

**Comment by SamMayWork** [comment] 2024-02-14 13:55
## Preliminary findings

Did a run of the tests for ~2 hours 30 minutes before the VM ran out of storage (note for anyone in the future: these tests produce a LOT of logs and data so you need a sizeable drive for prolonged test runs). Test run ended because the 64GB disk on the VM ran out of space.


```
INFO[2024-02-14T13:45:39.594] Cleaning up
2024/02/14 13:45:39.594586 WARN RESTY Using Basic Auth in HTTP mode is not secure, use HTTPS
INFO[2024-02-14T13:45:39.601] successfully deleted subscription with ID 10a44273-295a-443d-934f-342a7efe0587 for node URL http://localhost:5000
2024/02/14 13:45:39.601799 WARN RESTY Using Basic Auth in HTTP mode is not secure, use HTTPS
INFO[2024-02-14T13:45:39.605] successfully deleted subscription with ID 050e8f68-dc06-4ab0-b053-57d5eb143e45 for node URL http://localhost:5000
2024/02/14 13:45:39.605956 WARN RESTY Using Basic Auth in HTTP mode is not secure, use HTTPS
INFO[2024-02-14T13:45:39.609] successfully deleted subscription with ID 4183df5e-f160-411c-af64-4424c90e98d4 for node URL http://localhost:5000
2024/02/14 13:45:39.609660 WARN RESTY Using Basic Auth in HTTP mode is not secure, use HTTPS
INFO[2024-02-14T13:45:39.613] successfully deleted subscription with ID e89cd7b0-79ad-4663-8e83-7ba8a7f36876 for node URL http://localhost:5000
2024/02/14 13:45:39.613514 WARN RESTY Using Basic Auth in HTTP mode is not secure, use HTTPS
INFO[2024-02-14T13:45:39.630] successfully deleted listener with ID 68a82718-7fef-43a6-af30-f16b4a79a7d2 for node URL http://localhost:5000
2024/02/14 13:45:39.630183 WARN RESTY Using Basic Auth in HTTP mode is not secure, use HTTPS
INFO[2024-02-14T13:45:39.636] successfully deleted subscription with ID 9f389858-0926-4d34-972a-48ebc841dacd for node URL http://localhost:5001
2024/02/14 13:45:39.636757 WARN RESTY Using Basic Auth in HTTP mode is not secure, use HTTPS
INFO[2024-02-14T13:45:39.649] successfully deleted subscription with ID dbc5a858-39af-4e09-aa69-fcf9df1faa41 for node URL http://localhost:5001
2024/02/14 13:45:39.649365 WARN RESTY Using Basic Auth in HTTP mode is not secure, use HTTPS
INFO[2024-02-14T13:45:39.653] successfully deleted subscription with ID 8c1528be-5e80-49d1-bcb8-e405079e9c86 for node URL http://localhost:5001
2024/02/14 13:45:39.653407 WARN RESTY Using Basic Auth in HTTP mode is not secure, use HTTPS
INFO[2024-02-14T13:45:39.656] successfully deleted subscription with ID ab6ca4f2-6c2c-4a5d-8753-ba84d01d0438 for node URL http://localhost:5001
2024/02/14 13:45:39.656971 WARN RESTY Using Basic Auth in HTTP mode is not secure, use HTTPS
INFO[2024-02-14T13:45:39.666] successfully deleted listener with ID ee8ac535-7447-4118-bd79-67122977a86e for node URL http://localhost:5001
INFO[2024-02-14T13:45:39.666] Shutdown summary:
INFO[2024-02-14T13:45:39.666]  - Prometheus metric sent_mints_total        = 4833.000000
INFO[2024-02-14T13:45:39.666]  - Prometheus metric sent_mint_errors_total  = 0.000000
INFO[2024-02-14T13:45:39.666]  - Prometheus metric mint_token_balance      = 0.000000
INFO[2024-02-14T13:45:39.666]  - Prometheus metric received_events_total   = 324978.000000
INFO[2024-02-14T13:45:39.666]  - Prometheus metric incomplete_events_total = 0.000000
INFO[2024-02-14T13:45:39.666]  - Prometheus metric delinquent_msgs_total    = 0.000000
INFO[2024-02-14T13:45:39.666]  - Prometheus metric actions_submitted_total = 157840.000000
INFO[2024-02-14T13:45:39.666]  - Test duration: 2h25m26.591197105s
INFO[2024-02-14T13:45:39.666]  - Measured actions: 324978
INFO[2024-02-14T13:45:39.666]  - Measured send TPS: 37.513333
INFO[2024-02-14T13:45:39.666]  - Measured throughput: 37.239971
INFO[2024-02-14T13:45:39.666]  - Measured send duration: min: 9.452027ms, max: 856.108635ms, avg: 90ms
INFO[2024-02-14T13:45:39.666]  - Measured event receiving duration: min: 7.034177878s, max: 20.338569902s, avg: 10.41s
INFO[2024-02-14T13:45:39.666]  - Measured total duration: min: 7.034177878s, max: 20.338569902s, avg: 10.41s
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   350  100   350    0     0     11      0  0:00:31  0:00:30  0:00:01    88
Profiling data saved to perf-test-1-dot-3-stack.prof
^C[1]+  Done                    nohup ./start.sh &> ffperf.log
```

**Comment by SamMayWork** [comment] 2024-02-19 12:16
### The Plan

Here's the plan: we don't yet have an RC of 1.3, but it's not worth holding up the performance testing for that, if there's some major slow down then it's worth getting an idea of that now so we can start to work on the fixed required before we start the release process. 

With that in mind, we need to run a performance run of FireFly v1.2.0 and then a run of the current main branch to see if there's a performance difference. Given this is _super_ preliminary, it should be OK to use a shorter time frame to get a feeling for how quickly we're getting through transactions.

#### FireFly v1.2.0

Using the configuration below, we get the following results for an hour window of running the tests:

<details><summary>Expand for test configuration</summary>
<br>

```
nohup ./start.sh &> ffperf.log &
```
core-config.yml
```
log:
        level: debug
broadcast:
        batch:
                size: 200
                timeout: 1s
privatemessaging:
        batch:
                size: 200
                timeout: 1s
message:
        writer:
                count: 5
download:
        worker:
                count: 100
publicstorage:
                ipfs:
                        api:
                                requestTimeout: 2s
                        gateway:
                                requestTimeout: 2s
```
ethconnect.yml
```
rest:
  rest-gateway:
    maxTXWaitTime: 120
    maxInFlight: 200
    alwaysManageNonce: true
    attemptGapFill: true
    sendConcurrency: 3
    gasEstimationFactor: 2.0
confirmations:
  required: 5
debug:
  port: 6000
```
instances.yml
```
stackJSONPath: /home/ubuntu/.firefly/stacks/perf-1/stack.json

wsConfig:
  wsPath: /ws
  readBufferSize: 16000
  writeBufferSize: 16000
  initialDelay: 250ms
  maximumDelay: 30s
  initialConnectAttempts: 5
  heartbeatInterval: 5s

instances:
  - name: long-run
    tests: [{"name": "msg_broadcast", "workers":50},{"name": "msg_private", "workers":50},{"name": "blob_broadcast", "workers":30},{"name": "blob_private", "workers":30},{"name": "custom_ethereum_contract", "workers":20},{"name": "token_mint", "workers":10}]
    length: 500h
    sender: 0
    recipient: 1
    messageOptions:
      longMessage: false
    tokenOptions:
      tokenType: fungible
    contractOptions: {"address": "0x69eb9c6b573415d3a8ed2fd38c0f9685a36c8455"}
```
FireFly git commit:
```
dc86491bdf1adc9f25cdb410eacfcbf0e1fc23ba
```

</details>

<img width="1375" alt="image" src="https://github.com/hyperledger/firefly/assets/25016090/edd72705-5b9b-4fae-9f1e-37507859d0c4">

Measured TPS according to logs is hanging around `~40.26 TPS`

---

**Comment by SamMayWork** [comment] 2024-02-20 14:58
## Going Deeper

> *NOTE*: I'll be referring to '1.3' as what's currently in main, even though there isn't an RC

After performing 2 new runs of the performance test using the normal long-running configuration over the course of an hour, we get the following figures for inbound/outbound API response times:

```
| Route (Outbound Calls)                              1.2 avg   1.2 max   1.3 avg   1.3 max  |  Which faster?  |
| -------------------------------------------------------------------------------------------|                 |
| http://ipfs_0:5001/api/v0/add                       10.44ms   114.1ms   11.68ms   98.03ms  |       N/A       |
| http://dataexchange_0:3000/api/v1/blobs/default/    14.23ms   183.9ms   37.91ms   213.0ms  |       1.2       |
| http://dataexchange_0:3000/api/v1/transfers         27.22ms   76.45ms   22.74ms   95.65ms  |       N/A       |
| http://dataexchange_0:3000/api/v1/messages           9.67ms   75.15ms    5.32ms   68.73ms  |       N/A       |
| http://evmconnect_0:5008/                            9.74ms   108.8ms   21.74ms   151.9ms  |       1.2       |
| http://tokens_0_0:3000/api/v1/mint                  21.94ms   98.93ms   32.28ms   137.8ms  |       1.2       |


| Route (Inbound Calls)                               1.2 avg   1.2 max   1.3 avg   1.3 max  |  Which faster? |
| -------------------------------------------------------------------------------------------|                |
| /api/v1/namespaces/default/messages/broadcast       51.85ms   328.1ms   37.21ms   301.3ms  |       1.3!     |
| /api/v1/namespaces/default/messages/private         54.05ms   452.3ms   38.02ms   273.6ms  |       1.3!     |
| /api/v1/namespaces/default/data                     63.31ms   407.5ms   66.87ms   385.1ms  |       N/A      |
| /api/v1/namespaces/default/contracts/invoke         28.42ms   226.9ms   44.34ms   228.4ms  |       1.2      |
| /api/v1/namespaces/default/tokens/mint              78.77ms   376.8ms   77.63ms   287.7ms  |       N/A      |
```

*1- It's worth noting that these runs were performed for an hour, so the general trend is _probably_ reliable, but the specific figures should not be taken as gospel.

#### Preliminary conclusions

1. Calls outbound to DataExchange BLOBs API is _significantly_ faster on `v1.2.0` than on `v1.3.0`
2. Calls outbound to the EVM Connector are _significantly_ faster on `v1.2.0` than on `v1.3.0`
3. Calls outbound to the Token Connector are faster on `v1.2.0` than on `v1.3.0`
4. `v1.3.0` performs faster on all inbound API requests than `v1.2.0` apart from `/api/v1/namespaces/default/contracts/invoke (though this could be due to token connector slow down)

---

Given these figures it seems logical that the next areas for investigation are:
 - Data Exchange BLOBs API
 - EVM Connector transactions
 - Tokens Connector mint operations
 - Contract invoke (though this could be due to token connector slow down)

**Comment by SamMayWork** [comment] 2024-02-20 16:29
### Investigation

Going through each of the areas of investigation in no particular order because I like chaos...

<details><summary>(Inbound) Contract Invoke API</summary>
<br>

```
| Route (Inbound Calls)                               1.2 avg   1.2 max   1.3 avg   1.3 max  |  Which faster? |
| -------------------------------------------------------------------------------------------|                |
| /api/v1/namespaces/default/contracts/invoke         28.42ms   226.9ms   44.34ms   228.4ms  |       1.2      |
```

_Right_, so here we've gone from an average of `28.42ms` to `44.34ms` which is a ~60% increase in execution time, concerning. From the logs for each of the runs I conducted to produce the initial set of results, I've picked a transaction form both that show the difference in performance.

From `v1.2.0` I have `httpreq=qZ1KfQdQ` which took `21.64ms`
From `v1.3.0` I have `httpreq=9UDOTaTZ` which took `83.89ms`

---

_1.2 logs_
```
{"log":"[2024-02-19T19:59:15.382Z]  INFO --\u003e POST /api/v1/namespaces/default/contracts/invoke httpreq=qZ1KfQdQ pid=1 req=mCGqE1IS\n","stream":"stderr","time":"2024-02-19T19:59:15.383664552Z"}
{"log":"[2024-02-19T19:59:15.382Z] DEBUG SQL-\u003e begin dbtx=ZwLqWQBZ httpreq=qZ1KfQdQ pid=1 req=mCGqE1IS\n","stream":"stderr","time":"2024-02-19T19:59:15.383688129Z"}
{"log":"[2024-02-19T19:59:15.383Z] DEBUG SQL\u003c- begin dbtx=ZwLqWQBZ httpreq=qZ1KfQdQ pid=1 req=mCGqE1IS\n","stream":"stderr","time":"2024-02-19T19:59:15.383696645Z"}
{"log":"[2024-02-19T19:59:15.384Z] DEBUG SQL-\u003e insert transactions dbtx=ZwLqWQBZ httpreq=qZ1KfQdQ pid=1 req=mCGqE1IS\n","stream":"stderr","time":"2024-02-19T19:59:15.38455654Z"}
{"log":"[2024-02-19T19:59:15.385Z] DEBUG SQL\u003c- insert transactions sequences=[47918] dbtx=ZwLqWQBZ httpreq=qZ1KfQdQ pid=1 req=mCGqE1IS\n","stream":"stderr","time":"2024-02-19T19:59:15.385256478Z"}
{"log":"[2024-02-19T19:59:15.385Z] DEBUG SQL-\u003e insert operations dbtx=ZwLqWQBZ httpreq=qZ1KfQdQ pid=1 req=mCGqE1IS\n","stream":"stderr","time":"2024-02-19T19:59:15.385463333Z"}
{"log":"[2024-02-19T19:59:15.386Z] DEBUG SQL\u003c- insert operations sequences=[138572] dbtx=ZwLqWQBZ httpreq=qZ1KfQdQ pid=1 req=mCGqE1IS\n","stream":"stderr","time":"2024-02-19T19:59:15.386316466Z"}
{"log":"[2024-02-19T19:59:15.386Z] DEBUG SQL-\u003e lock default dbtx=ZwLqWQBZ httpreq=qZ1KfQdQ pid=1 req=mCGqE1IS\n","stream":"stderr","time":"2024-02-19T19:59:15.38660824Z"}
{"log":"[2024-02-19T19:59:15.386Z] DEBUG SQL\u003c- lock default dbtx=ZwLqWQBZ httpreq=qZ1KfQdQ pid=1 req=mCGqE1IS\n","stream":"stderr","time":"2024-02-19T19:59:15.387084482Z"}
{"log":"[2024-02-19T19:59:15.387Z] DEBUG SQL-\u003e insert events dbtx=ZwLqWQBZ httpreq=qZ1KfQdQ pid=1 req=mCGqE1IS\n","stream":"stderr","time":"2024-02-19T19:59:15.387300098Z"}
{"log":"[2024-02-19T19:59:15.390Z] DEBUG SQL\u003c- insert events sequences=[372131] dbtx=ZwLqWQBZ httpreq=qZ1KfQdQ pid=1 req=mCGqE1IS\n","stream":"stderr","time":"2024-02-19T19:59:15.390809911Z"}
{"log":"[2024-02-19T19:59:15.390Z] DEBUG SQL-\u003e commit dbtx=ZwLqWQBZ httpreq=qZ1KfQdQ pid=1 req=mCGqE1IS\n","stream":"stderr","time":"2024-02-19T19:59:15.390826751Z"}
{"log":"[2024-02-19T19:59:15.392Z] DEBUG SQL\u003c- commit dbtx=ZwLqWQBZ httpreq=qZ1KfQdQ pid=1 req=mCGqE1IS\n","stream":"stderr","time":"2024-02-19T19:59:15.392218175Z"}
{"log":"[2024-02-19T19:59:15.392Z]  INFO Emitted transaction_submitted event 314edbfc-f82d-4a32-a58e-317c13e09842 for default:7eb9f31f-48a0-4979-85f4-008b3a63d901 (correlator=,topic=contract_invoke) dbtx=ZwLqWQBZ httpreq=qZ1KfQdQ pid=1 req=mCGqE1IS\n","stream":"stderr","time":"2024-02-19T19:59:15.392479498Z"}
{"log":"[2024-02-19T19:59:15.392Z]  INFO Executing blockchain_invoke operation 1c2433e4-efd5-49ea-8cd5-6a8d496f8baf via handler ContractManager httpreq=qZ1KfQdQ pid=1 req=mCGqE1IS\n","stream":"stderr","time":"2024-02-19T19:59:15.39296641Z"}
{"log":"[2024-02-19T19:59:15.404Z]  INFO \u003c-- POST /api/v1/namespaces/default/contracts/invoke [202] (21.64ms) httpreq=qZ1KfQdQ pid=1 req=mCGqE1IS\n","stream":"stderr","time":"2024-02-19T19:59:15.406246777Z"}
```

_1.3 logs_

```
{"log":"[2024-02-19T13:57:59.874Z]  INFO --\u003e POST /api/v1/namespaces/default/contracts/invoke httpreq=9UDOTaTZ pid=1 req=TB5NNKuM\n","stream":"stderr","time":"2024-02-19T13:57:59.876572405Z"}
{"log":"[2024-02-19T13:57:59.876Z] DEBUG Validating method 'methodhash_set_27c24ee2991b7efee363af9e49f8cfda448be98036b314746c9bbeb81ebbc2d4' (cacheMiss=false) httpreq=9UDOTaTZ pid=1 req=TB5NNKuM\n","stream":"stderr","time":"2024-02-19T13:57:59.877197117Z"}
{"log":"[2024-02-19T13:57:59.893Z]  INFO Executing blockchain_invoke operation ec41af8e-51d7-454c-a3a7-e7d95d4549ae via handler ContractManager httpreq=9UDOTaTZ pid=1 req=TB5NNKuM\n","stream":"stderr","time":"2024-02-19T13:57:59.894025396Z"}
{"log":"[2024-02-19T13:57:59.893Z] DEBUG Validating method 'methodhash_set_27c24ee2991b7efee363af9e49f8cfda448be98036b314746c9bbeb81ebbc2d4' (cacheMiss=false) httpreq=9UDOTaTZ pid=1 req=TB5NNKuM\n","stream":"stderr","time":"2024-02-19T13:57:59.894051915Z"}
{"log":"[2024-02-19T13:57:59.894Z] DEBUG EVMConnectorBody: {\"from\":\"0x4c765d85923692812d4a9c72e599b5565e49d943\",\"headers\":{\"type\":\"SendTransaction\",\"id\":\"default:ec41af8e-51d7-454c-a3a7-e7d95d4549ae\"},\"method\":{\"type\":\"function\",\"name\":\"set\",\"inputs\":[{\"name\":\"newValue\",\"type\":\"uint256\"}],\"outputs\":[]},\"params\":[164],\"to\":\"0x457e54a0e07aae6332ffdeea59e3c5580810ba0a\"} httpreq=9UDOTaTZ pid=1 req=TB5NNKuM\n","stream":"stderr","time":"2024-02-19T13:57:59.894158763Z"}
{"log":"[2024-02-19T13:57:59.960Z]  INFO \u003c-- POST /api/v1/namespaces/default/contracts/invoke [202] (83.89ms) httpreq=9UDOTaTZ pid=1 req=TB5NNKuM\n","stream":"stderr","time":"2024-02-19T13:57:59.962258998Z"}
```

Noting the big difference in logs shows that there's definitely some implementation changes here for us to dig into... Time to dig into the code...

<img width="1086" alt="image" src="https://github.com/hyperledger/firefly/assets/25016090/188f9317-5207-4e8d-ae4c-9d877e7f8d81">

Bingpot! - Changes within the last 8 months.... Which is this PR: https://github.com/hyperledger/firefly/pull/1354, curiously labelled 'Further optimize blockchain transaction inserts to DB'. Think there's more to the story here to uncover...

</details>

**Comment by SamMayWork** [comment] 2024-02-21 11:18
## Long-Running Test

Previously, tests have been running for < a couple of hours at most, we're at the point of now needing to run longer tests to observe what transaction speed/throughput is looking like. We're going to the run the same suite as run for 1.2 for at least 4-5 days and then compare results.

**Comment by EnriqueL8** [comment] 2024-04-10 09:04
Have posted on [ Hardening 1.3 release  ](https://github.com/hyperledger/firefly/issues/1470) the results from a run, the problem with the difference in confirmed over submitted was due to the metrics not being correctly added, should be fixed by https://github.com/hyperledger/firefly/pull/1490

**Comment by EnriqueL8** [comment] 2024-05-22 12:22
This is done

**Closed by EnriqueL8** 2024-05-22 12:22 UTC
