### ISSUE TITLE
Perf-Test: Websocket events not being sent

### ISSUE THREAD

**Issue by eberger727** [hyperledger/firefly#481] opened 2022-02-04 21:43 UTC
The FireFly performance tests use go routines to send multiple requests to an API at the same time. These routines then wait for their specific websocket event to confirm their transaction was completed before moving on to its next task. 

In v0.11.5 of FireFly, these websocket events were being sent correctly, allowing for workers to proceed as expected.

In v0.12.0 of FireFly, one websocket event is received, then no more websocket events come through, resulting in workers not being able to confirm that their transaction completed and moving on to their next task.

[ff-perf v0-11-5.log](https://github.com/hyperledger/firefly/files/8006353/v0-11-5.log)
[ff-perf v0-12-0.log](https://github.com/hyperledger/firefly/files/8006354/v0-12-0.log)
[v0-12-0-ff_core.log](https://github.com/hyperledger/firefly/files/8006409/v0-12-0-ff_core.log)

**Comment by peterbroadhurst** [comment] 2022-02-04 21:53
This is an interesting log entry:

```
[2022-02-04T21:43:17.643Z] DEBUG Message 627e73f3-cee3-4ff1-93cf-049fb03b9989 pinned at sequence 15 blocked by earlier context 37a8eec1ce19687d132fe29051dca629d164e2c4958ba141d5f4133a33f0688f at sequence 14 dbtx=rI1QGY1p pid=1 role=aggregator
```

**Comment by eberger727** [comment] 2022-02-04 21:58
Fresh logs with timestamps
[v0-12-0-ff_core.log](https://github.com/hyperledger/firefly/files/8006470/v0-12-0-ff_core.log)
[v0-12-0-ff_eth.log](https://github.com/hyperledger/firefly/files/8006471/v0-12-0-ff_eth.log)
[v0-12-0.log](https://github.com/hyperledger/firefly/files/8006472/v0-12-0.log)

**Comment by peterbroadhurst** [comment] 2022-02-04 21:58
fyi @awrichar - investigating, but looks like we might not be resolving the pins any more in the aggregator.
Possibly this fell out with the aggregator `PreFinalize`/`Finalize` logic.
Digging more.

**Comment by peterbroadhurst** [comment] 2022-02-04 21:59
The only `UpdateNextPin` I can see in the code is in a masked (private transfer) branch

**Comment by peterbroadhurst** [comment] 2022-02-04 22:00
https://github.com/hyperledger/firefly/blob/f262c5c30c06dbc8d9c282a5620906763155ce00/internal/events/aggregator.go#L356-L374

**Comment by peterbroadhurst** [comment] 2022-02-04 22:00
The E2E might have missed this, as it doesn't send multiple messages sequentially on the same topic - maybe something to update.

**Comment by peterbroadhurst** [comment] 2022-02-04 22:01
Before we had `SetPinDispatched`.... which is still there in `Finalize` 🤔

**Comment by peterbroadhurst** [comment] 2022-02-04 22:03
Aha - got it.
The problem is all these messages are in a batch. We don't now do `SetPinDispatched` until the end, but of course this means that all the messages apart from the first one fail the check of whether they are blocked within the main processing (before the `Finalize` stage)

**Comment by peterbroadhurst** [comment] 2022-02-04 23:16
My plan is to create a batch state type object, that provides retrieve+update actions on pins/nextpins. These will read the database entry, and cache it. Then updates will be only in memory.

The `Finalize` then becomes a "flush" of that state.

**Closed** 2022-02-09 22:14 UTC
