### ISSUE TITLE
Field-level descriptions on Swagger / OpenAPI

### ISSUE THREAD

**Issue by peterbroadhurst** [hyperledger/firefly#111] opened 2021-07-01 17:47 UTC
- [ ] Support field-level i18n description keys on structures
  - Needs FireFly extensions to the Struct->JSON Schema parser
  - Could be contributed back `openapi3gen` in that community: https://github.com/getkin/kin-openapi
- [ ] Enhance enums (types etc.) so they show the possible values
   - [ ] Translation keys for each value
- [ ] Go through all the `fftypes` structures and add i18n keys
   > - This could be a separate work item to the others, done by a different person, as it needs field level knowledge

@gabriel-indik was pointing out the importance of this one in a conversation, as he was exploring the Swagger

**Comment by peterbroadhurst** [comment] 2021-08-25 13:22
After a bit of investigation, it seemed like we would struggle to continue to use the struct->schema generator in `kin-openapi` without an extension, so I've made a proposal to that project to get the ball rolling.
We will see what the feedback there is on the approach, before continuing. So I'm going to take ownership of this issue for now.
https://github.com/getkin/kin-openapi/pull/411

**Comment by shorsher** [comment] 2022-04-26 19:05
duplicate of https://github.com/hyperledger/firefly/issues/402 and addressed in v1.

**Closed by shorsher** 2022-04-26 19:05 UTC
Labels: enhancement
